### ISSUE TITLE
Chore: License problems

### ISSUE THREAD

**Issue by hycdong** [apache/incubator-pegasus#823]
## Introduction
As Pegasus has already donated to ASF, all files are expected to have license header, either ASF license, or thirdparty copyright. 

Pegasus is a license-complex project, includes rDSN, a distributed system framework maintained by Microsoft, whose license is MIT. Xiaomi engineers fork rDSN repo and developed pegasus based on it, so some files' copyrights belongs to Xiaomi, whose license is Apache 2.0. Based on history problems, there are still some files lack of any license header or copyright. 

This issue is to record all of them, and raise the discussion about the Pegasus license problems.

## Files lack of license header
There are sereval types files without license header:
- Source files (`.h` or `.cpp`)
- CMakeList files (`.txt` etc)
- Config files (`.ini`)
- Scripts (`.sh`, `.py`)
- Others (`.md`, `.thrift` etc)

Detailed file list can be found in this issue below.

## TODO
- [ ] Add license headers for files without it
- [ ] Update LICENSE file with all 3rd party license

### Source files
- [ ] rdsn/include/dsn/cpp/serialization_helper/dsn.layer2_types.h (thrift-auto-generated)
- [ ] rdsn/include/dsn/cpp/serialization_helper/dsn_types.h
- [ ] rdsn/include/dsn/dist/replication/replication_enums.h
- [ ] rdsn/include/dsn/dist/replication/storage_serverlet.h
- [ ] rdsn/include/dsn/tool-api/threadpool_code.h
- [ ] rdsn/include/dsn/utility/binary_reader.h
- [ ] rdsn/include/dsn/utility/binary_writer.h
- [ ] rdsn/include/dsn/utility/crc.h
- [ ] rdsn/include/dsn/utility/error_code.h
- [ ] rdsn/include/dsn/utility/strings.h
- [ ] rdsn/src/failure_detector/test/failure_detector.cpp
- [ ] rdsn/src/meta/test/server_state_test.cpp
- [ ] rdsn/src/meta/test/meta_state/meta_state_service.cpp
- [ ] rdsn/src/meta/test/meta_partition_guardian_test.cpp
- [ ] rdsn/src/meta/test/state_sync_test.cpp
- [ ] rdsn/src/meta/test/meta_data.cpp
- [ ] rdsn/src/meta/test/dump_file.cpp
- [ ] rdsn/src/meta/test/json_compacity.cpp
- [ ] rdsn/src/meta/test/balancer_validator.cpp
- [ ] rdsn/src/meta/test/misc/misc.cpp
- [ ] rdsn/src/meta/test/balancer_simulator/balancer_simulator.cpp
- [ ] rdsn/src/meta/server_load_balancer.cpp
- [ ] rdsn/src/nfs/nfs_node.cpp
- [ ] rdsn/src/nfs/test/main.cpp
- [ ] rdsn/src/perf_counter/perf_counter.cpp
- [ ] rdsn/src/replica/storage/simple_kv/simple_kv.client.h
- [ ] rdsn/src/replica/test/replication_service_test_app.h
- [ ] rdsn/src/runtime/build_config.h
- [ ] rdsn/src/runtime/dsn.layer2_types.cpp (thrift-auto-generated)
- [ ] rdsn/src/utils/test/autoref_ptr_test.cpp
- [ ] rdsn/src/utils/binary_writer.cpp
- [ ] rdsn/src/utils/safe_strerror_posix.cpp
- [ ] rdsn/src/utils/binary_reader.cpp
- [ ] rdsn/src/utils/crc.cpp
- [ ] src/base/rrdb_types.cpp (thrift-auto-generated)
- [ ] src/include/rrdb/rrdb_types.h (thrift-auto-generated)
- [ ] src/include/pegasus/git_commit.h (build-generated gitignored)

### Compile files
 - [ ] rdsn/bin/dsn.cmake
 - [ ] rdsn/src/aio/CMakeLists.txt
 - [ ] rdsn/src/aio/test/CMakeLists.txt
 - [ ] rdsn/src/block_service/fds/CMakeLists.txt
 - [ ] rdsn/src/block_service/hdfs/CMakeLists.txt
 - [ ] rdsn/src/block_service/local/CMakeLists.txt
 - [ ] rdsn/src/client/CMakeLists.txt
 - [ ] rdsn/src/common/CMakeLists.txt
 - [ ] rdsn/src/common/test/CMakeLists.txt
 - [ ] rdsn/src/failure_detector/CMakeLists.txt
 - [ ] rdsn/src/failure_detector/test/CMakeLists.txt
 - [ ] rdsn/src/http/test/CMakeLists.txt
 - [ ] rdsn/src/meta/CMakeLists.txt
 - [ ] rdsn/src/meta/test/balancer_simulator/CMakeLists.txt
 - [ ] rdsn/src/meta/test/meta_state/CMakeLists.txt
 - [ ] rdsn/src/meta/test/CMakeLists.txt
 - [ ] rdsn/src/nfs/CMakeLists.txt
 - [ ] rdsn/src/nfs/test/CMakeLists.txt
 - [ ] rdsn/src/perf_counter/CMakeLists.txt
 - [ ] rdsn/src/perf_counter/test/CMakeLists.txt
 - [ ] rdsn/src/remote_cmd/CMakeLists.txt
 - [ ] rdsn/src/replica/split/test/CMakeLists.txt
 - [ ] rdsn/src/replica/CMakeLists.txt
 - [ ] rdsn/src/replica/duplication/test/CMakeLists.txt
 - [ ] rdsn/src/replica/test/CMakeLists.txt
 - [ ] rdsn/src/replica/backup/test/CMakeLists.txt
 - [ ] rdsn/src/replica/bulk_load/test/CMakeLists.txt
 - [ ] rdsn/src/runtime/CMakeLists.txt
 - [ ] rdsn/src/runtime/test/CMakeLists.txt
 - [ ] rdsn/src/runtime/task/CMakeLists.txt
 - [ ] rdsn/src/runtime/security/CMakeLists.txt
 - [ ] rdsn/src/runtime/rpc/CMakeLists.txt
 - [ ] rdsn/src/tools/CMakeLists.txt
 - [ ] rdsn/src/utils/CMakeLists.txt
 - [ ] rdsn/src/utils/test/CMakeLists.txt
 - [ ] rdsn/src/zookeeper/CMakeLists.txt
 - [ ] rdsn/src/zookeeper/test/CMakeLists.txt
 - [ ] rdsn/src/replica/storage/CMakeLists.txt
 - [ ] rdsn/src/replica/storage/simple_kv/CMakeLists.txt
 - [ ] rdsn/src/replica/storage/simple_kv/test/CMakeLists.txt
 - [ ] rdsn/src/CMakeLists.txt

### Scripts
 - [ ] rdsn/scripts/linux/learn_stat.py
 - [ ] rdsn/scripts/linux/stop_zk.sh
 - [ ] rdsn/scripts/linux/run-clang-format.sh
 - [ ] rdsn/scripts/linux/install.sh
 - [ ] rdsn/scripts/linux/start_zk.sh
 - [ ] rdsn/scripts/linux/clear_zk.sh
 - [ ] rdsn/scripts/linux/build.sh
 - [ ] rdsn/scripts/linux/run-clang-format.py
 - [ ] rdsn/src/aio/test/clear.sh
 - [ ] rdsn/src/aio/test/run.sh
 - [ ] rdsn/src/common/test/run.sh
 - [ ] rdsn/src/failure_detector/test/clear.sh
 - [ ] rdsn/src/failure_detector/test/run.sh
 - [ ] rdsn/src/http/test/run.sh
 - [ ] rdsn/src/meta/test/meta_state/clear.sh
 - [ ] rdsn/src/meta/test/meta_state/run.sh
 - [ ] rdsn/src/meta/test/clear.sh
 - [ ] rdsn/src/nfs/test/clear.sh
 - [ ] rdsn/src/perf_counter/test/clear.sh
 - [ ] rdsn/src/perf_counter/test/run.sh
 - [ ] rdsn/src/replica/split/test/run.sh
 - [ ] rdsn/src/replica/duplication/test/run.sh
 - [ ] rdsn/src/replica/test/run.sh
 - [ ] rdsn/src/replica/backup/test/run.sh
 - [ ] rdsn/src/replica/bulk_load/test/run.sh
 - [ ] rdsn/src/runtime/test/run.sh
 - [ ] rdsn/src/runtime/test/clear.sh
 - [ ] rdsn/src/runtime/test/run.sh
 - [ ] rdsn/src/runtime/test/clear.sh
 - [ ] rdsn/src/utils/test/clear.sh
 - [ ] rdsn/src/utils/test/run.sh
 - [ ] rdsn/src/zookeeper/test/clear.sh
 - [ ] rdsn/src/zookeeper/test/run.sh
 - [ ] rdsn/src/replica/storage/simple_kv/clear.sh
 - [ ] rdsn/src/replica/storage/simple_kv/test/addcase.sh
 - [ ] rdsn/src/replica/storage/simple_kv/run.sh
 - [ ] rdsn/src/replica/storage/simple_kv/test/clear.sh
 - [ ] rdsn/src/replica/storage/simple_kv/test/run.sh
 - [ ] rdsn/src/replica/storage/simple_kv/clear.sh

### Config files(.ini files)
- [ ] rdsn/src/aio/test/config.ini
- [ ] rdsn/src/block_service/test/config-test.ini
- [ ] rdsn/src/common/test/config-test.ini
- [ ] rdsn/src/failure_detector/test/config-test.ini
- [ ] rdsn/src/failure_detector/test/config-whitelist-test.ini
- [ ] rdsn/src/failure_detector/test/config-whitelist-test-failed.ini
- [ ] rdsn/src/nfs/test/config.ini
- [ ] rdsn/src/replica/split/test/config-test.ini
- [ ] rdsn/src/replica/duplication/test/config-test.ini
- [ ] rdsn/src/replica/test/config-test.ini
- [ ] rdsn/src/replica/backup/test/config-test.ini
- [ ] rdsn/src/replica/bulk_load/test/config-test.ini
- [ ] all `ini` files below rdsn/src/replica/storage/simple_kv
- [ ] rdsn/src/runtime/test/config-test.ini
- [ ] rdsn/src/runtime/test/config-test-sim.ini
- [ ] rdsn/src/runtime/test/config-test-corrupt-message.ini
- [ ] rdsn/src/utils/test/config-sample.ini
- [ ] rdsn/src/utils/test/config-dup-key.ini
- [ ] rdsn/src/utils/test/config-unmatch-section.ini
- [ ] rdsn/src/utils/test/config-no-section.ini
- [ ] rdsn/src/utils/test/config-bad-section.ini
- [ ] rdsn/src/utils/test/config-empty.ini
- [ ] rdsn/src/utils/test/config-no-key.ini
- [ ] rdsn/src/utils/test/config-null-section.ini
- [ ] rdsn/src/utils/test/config-dup-section.ini
- [ ] rdsn/src/zookeeper/test/config-test.ini
- [ ] src/base/test/config.ini
- [ ] src/geo/test/config.ini
- [ ] src/geo/bench/config.ini
- [ ] src/redis_protocol/proxy_ut/config.ini
- [ ] src/redis_protocol/proxy/config.ini
- [ ] src/sample/config.ini
- [ ] src/server/test/config.ini
- [ ] src/server/config.ini
- [ ] src/server/config.min.ini
- [ ] src/shell/config.ini
- [ ] src/test/pressure_test/config-pressure.ini
- [ ] src/test/upgrade_test/config.ini
- [ ] src/test/function_test/config.ini
- [ ] src/test/bench_test/config.ini
- [ ] src/test/kill_test/config.ini

### Others
- [ ] rdsn/src/aio/test/copy_source.txt
- [ ] rdsn/src/failure_detector/fd.thrift
- [ ] rdsn/src/failure_detector/test/gtest.filter
- [ ] rdsn/src/meta/test/meta_state/clear.cmd
- [ ] rdsn/src/meta/test/meta_state/gtest.filter
- [ ] rdsn/src/meta/test/suite1
- [ ] rdsn/src/meta/test/suite2
- [ ] rdsn/src/nfs/nfs.thrift
- [ ] rdsn/src/nfs/test/nfs_test_file1
- [ ] rdsn/src/nfs/test/nfs_test_file2
- [ ] rdsn/src/remote_cmd/command.thrift
- [ ] rdsn/src/replica/duplication/test/log.1.0.all_loaded_are_write_empties
- [ ] rdsn/src/replica/duplication/test/log.1.0.handle_real_private_log
- [ ] rdsn/src/replica/duplication/test/log.1.0.handle_real_private_log2
- [ ] all `act` files below rdsn/src/replica/storage/simple_kv
- [ ] rdsn/src/runtime/test/gtest.filter
- [ ] rdsn/src/runtime/test/command.txt
- [ ] rdsn/src/dsn.thrift
- [ ] rdsn/src/dsn.layer2.thrift
- [ ] rfcs/2021-05-27-user-specified-compaction.md
- [ ] rfcs/2021-02-22-disk-migrator.md
- [ ] rfcs/2020-12-15-meta-proxy.md
- [ ] rfcs/2020-08-27-metric-api.md
- [ ] rfcs/2020-10-09-data-version-v3.md
- [ ] src/sample/README
- [ ] README.md

**Comment by nguyenm100** [comment]
Hi, I noticed that license problem is one of the issues highlight by apache (https://whimsy.apache.org/board/minutes/Pegasus.html) to prevent upgrade out of incubation.  Is this expected to be resolved relatively soon? (next 2-3mo?).  tx

**Comment by acelyc111** [comment]
> Hi, I noticed that license problem is one of the issues highlight by apache (https://whimsy.apache.org/board/minutes/Pegasus.html) to prevent upgrade out of incubation. Is this expected to be resolved relatively soon? (next 2-3mo?). tx

Now we are going to resolve these problems.
